'use strict';var swiper2;var body=jQuery('body');var mainSlider=jQuery('#main-slider');var imageCarousel=jQuery('.img-carousel');var partnersCarousel=jQuery('#partners');var testimonialsCarousel=jQuery('#testimonials');var testimonialsCarouselAlt=jQuery('#testimonials-alt');var carCarousel=jQuery('.car-carousel');var topProductsCarousel=jQuery('#top-products-carousel');var featuredProductsCarousel=jQuery('#featured-products-carousel');var sidebarProductsCarousel=jQuery('#sidebar-products-carousel');var hotDealsCarousel=jQuery('#hot-deals-carousel');var owlCarouselSelector=jQuery('.owl-carousel');var isotopeContainer=jQuery('.isotope');var isotopeFiltrable=jQuery('#filtrable a');var toTop=jQuery('#to-top');var hover=jQuery('.thumbnail');var navigation=jQuery('.navigation');var superfishMenu=jQuery('ul.sf-menu');var priceSliderRange=jQuery('#slider-range');var swiperOffersBest=jQuery('.swiper--offers-best .swiper-container');var swiperOffersPopular=jQuery('.swiper--offers-popular .swiper-container');var swiperOffersEconomic=jQuery('.swiper--offers-economic .swiper-container');var swiperSlider1x1=jQuery('#swiperSlider1x1');var swiperSlider1x2=jQuery('#swiperSlider1x2');var swiperSlider1x3=jQuery('#swiperSlider1x3');var swiperSlider1x4=jQuery('#swiperSlider1x4');var swiperSlider1x5=jQuery('#swiperSlider1x5');var swiperSlider2x1=jQuery('#swiperSlider2x1');var swiperSlider2x2=jQuery('#swiperSlider2x2');var swiperSlider2x3=jQuery('#swiperSlider2x3');var swiperSlider2x4=jQuery('#swiperSlider2x4');var swiperSlider2x5=jQuery('#swiperSlider2x5');var swiperSlider3x1=jQuery('#swiperSlider3x1');var swiperSlider3x2=jQuery('#swiperSlider3x2');var swiperSlider3x3=jQuery('#swiperSlider3x3');var swiperSlider3x4=jQuery('#swiperSlider3x4');var swiperSlider3x5=jQuery('#swiperSlider3x5');var swiperSlider4x1=jQuery('#swiperSlider4x1');var swiperSlider4x2=jQuery('#swiperSlider4x2');var swiperSlider4x3=jQuery('#swiperSlider4x3');var swiperSlider4x4=jQuery('#swiperSlider4x4');var swiperSlider4x5=jQuery('#swiperSlider4x5');jQuery.fn.slideFadeToggle=function(speed,easing,callback){return this.animate({opacity:'toggle',height:'toggle'},speed,easing,callback);};jQuery.fn.slideFadeIn=function(speed,easing,callback){return this.animate({opacity:'show',height:'show'},speed,easing,callback);};jQuery.fn.slideFadeOut=function(speed,easing,callback){return this.animate({opacity:'hide',height:'hide'},speed,easing,callback);};jQuery(document).ready(function($){$('#tabs1 li a').click(function(){$(window).trigger('resize');});if(jQuery().sticky){jQuery('.header.fixed').sticky({topSpacing:0});}
if(jQuery().superfish){superfishMenu.superfish();}
jQuery('.menu-toggle').on('click',function(){if(navigation.hasClass('opened')){navigation.removeClass('opened').addClass('closed');}else{navigation.removeClass('closed').addClass('opened');}});jQuery('.menu-toggle-close').on('click',function(){if(navigation.hasClass('opened')){navigation.removeClass('opened').addClass('closed');}else{navigation.removeClass('closed').addClass('opened');}});if(jQuery('.content-area.scroll').length){jQuery('.open-close-area').on('click',function(){if(jQuery('.wrapper').hasClass('opened')){jQuery('.wrapper').removeClass('opened').addClass('closed');}else{jQuery('.wrapper').removeClass('closed').addClass('opened');}});}
jQuery('.sf-menu a, .scroll-to').on('click',function(){jQuery('.sf-menu a').removeClass('active');jQuery(this).addClass('active');jQuery('html, body').animate({scrollTop:jQuery(jQuery(this).attr('href')).offset().top},{duration:1200,easing:'easeInOutExpo'});return false;});if(jQuery().selectpicker){jQuery('.selectpicker').selectpicker();}
if(jQuery().prettyPhoto){jQuery("a[data-gal^='prettyPhoto']").prettyPhoto({theme:'dark_square'});}
jQuery(window).scroll(function(){if(jQuery(this).scrollTop()>1){toTop.css({bottom:'15px'});}else{toTop.css({bottom:'-100px'});}});toTop.on('click',function(){jQuery('html, body').animate({scrollTop:'0px'},800);return false;});jQuery('[data-toggle="tabajax"]').on('click',function(e){e.preventDefault();var loadurl=jQuery(this).attr('href');var targ=jQuery(this).attr('data-target');jQuery.get(loadurl,function(data){jQuery(targ).html(data);});jQuery(this).tab('show');});if(jQuery().owlCarousel){var owl=jQuery('.owl-carousel');owl.on('changed.owl.carousel',function(e){if(jQuery().prettyPhoto){jQuery("a[data-gal^='prettyPhoto']").prettyPhoto({theme:'dark_square'});}});if(mainSlider.length){var items=jQuery('#main-slider .item');if(items.length>2){mainSlider.owlCarousel({rtl:rentit_obj.rtl,autoplay:false,autoplayHoverPause:true,loop:true,margin:0,dots:true,nav:true,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsiveRefreshRate:100,responsive:{0:{items:1},479:{items:1},768:{items:1},991:{items:1},1024:{items:1}}});}else{mainSlider.owlCarousel({rtl:rentit_obj.rtl,autoplay:false,autoplayHoverPause:true,loop:false,margin:0,dots:true,nav:true,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsiveRefreshRate:100,responsive:{0:{items:1},479:{items:1},768:{items:1},991:{items:1},1024:{items:1}}});}}
if(topProductsCarousel.length){topProductsCarousel.owlCarousel({rtl:rentit_obj.rtl,autoplay:false,loop:true,margin:30,dots:false,nav:true,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsive:{0:{items:1},479:{items:2},768:{items:3},991:{items:4},1024:{items:5},1280:{items:6}}});}
if(featuredProductsCarousel.length){featuredProductsCarousel.owlCarousel({rtl:rentit_obj.rtl,autoplay:false,loop:true,margin:30,dots:false,nav:true,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsive:{0:{items:1},479:{items:1},768:{items:2},991:{items:3},1024:{items:4}}});}
if(sidebarProductsCarousel.length){sidebarProductsCarousel.owlCarousel({rtl:rentit_obj.rtl,autoplay:false,loop:true,margin:30,dots:true,nav:false,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsive:{0:{items:1},479:{items:1},768:{items:1},991:{items:1},1024:{items:1}}});}
if(partnersCarousel.length){partnersCarousel.owlCarousel({rtl:rentit_obj.rtl,autoplay:false,loop:true,margin:30,dots:false,nav:true,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsive:{0:{items:1},479:{items:2},768:{items:3},991:{items:4},1024:{items:5},1280:{items:6}}});}
if(testimonialsCarousel.length){testimonialsCarousel.owlCarousel({rtl:rentit_obj.rtl,autoplay:false,loop:false,margin:0,dots:true,nav:false,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsive:{0:{items:1},479:{items:1},768:{items:1},991:{items:1},1024:{items:1},1280:{items:1}}});}
if(testimonialsCarouselAlt.length){testimonialsCarouselAlt.owlCarousel({rtl:rentit_obj.rtl,autoplay:false,loop:false,margin:0,dots:true,nav:false,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsive:{0:{items:1},479:{items:1},768:{items:1},991:{items:2},1024:{items:2},1280:{items:2}}});}
if(imageCarousel.length){imageCarousel.each(function(e){var items=$(this).find('.item');if(items.length>1){$(this).owlCarousel({rtl:rentit_obj.rtl,autoplay:false,loop:true,margin:0,dots:true,nav:true,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsiveRefreshRate:100,responsive:{0:{items:1},479:{items:1},768:{items:1},991:{items:1},1024:{items:1}}});}else{$(this).owlCarousel({rtl:rentit_obj.rtl,autoplay:false,loop:false,margin:0,dots:false,nav:false,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsiveRefreshRate:100,responsive:{0:{items:1},479:{items:1},768:{items:1},991:{items:1},1024:{items:1}}});}});}
if(carCarousel.length){carCarousel.owlCarousel({rtl:rentit_obj.rtl,autoplay:false,loop:true,margin:30,dots:false,nav:true,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsiveRefreshRate:100,responsive:{0:{items:1},479:{items:1},768:{items:2},991:{items:3},1024:{items:3}}});}
jQuery('a[data-toggle="tab"]').on('show.bs.tab',function(e){updater();});jQuery('a[data-toggle="tab"]').on('shown.bs.tab',function(e){updater();});}
if(jQuery().swiper){var swiperOffersBest4=new Swiper(jQuery('.swiper--new'),{direction:'horizontal',slidesPerView:3,spaceBetween:30,loop:true,paginationClickable:true,pagination:'.swiper-pagination',nextButton:'.swiper-button-next',prevButton:'.swiper-button-prev'});if(swiperOffersBest.length){swiperOffersBest=new Swiper(swiperOffersBest,{direction:'horizontal',slidesPerView:3,spaceBetween:30,loop:true,paginationClickable:true,pagination:'.swiper-pagination',nextButton:'.swiper-button-next',prevButton:'.swiper-button-prev'});}
if(swiperOffersPopular.length){swiperOffersPopular=new Swiper(swiperOffersPopular,{direction:'horizontal',slidesPerView:3,spaceBetween:30,loop:true,paginationClickable:true,pagination:'.swiper-pagination',nextButton:'.swiper-button-next',prevButton:'.swiper-button-prev'});}
if(swiperOffersEconomic.length){swiperOffersEconomic=new Swiper(swiperOffersEconomic,{direction:'horizontal',slidesPerView:3,spaceBetween:30,loop:true,paginationClickable:true,pagination:'.swiper-pagination',nextButton:'.swiper-button-next',prevButton:'.swiper-button-prev'});}
var swiper=new Swiper('.navigation',{scrollbar:'.swiper-scrollbar',direction:'vertical',slidesPerView:'auto',mousewheelControl:true,freeMode:true});if(jQuery('.content-area.scroll').length){var i=0;swiper2=new Swiper('.content-area.scroll',{scrollbar:'.swiper-scrollbar',direction:'vertical',slidesPerView:'auto',mousewheelControl:true,scrollbarDraggable:true,mousewheelForceToAxis:true,keyboardControl:true,freeMode:true,onTouchStart:function(){},onProgress:function(e){if(i>1){loadajaxonmap(i);}
i++;}});}
if(swiperSlider1x4.length){swiperSlider1x4=new Swiper(swiperSlider1x4,{pagination:'#swiperSlider1x4 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider1x5.length){swiperSlider1x5=new Swiper(swiperSlider1x5,{pagination:'#swiperSlider1x5 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider2x1.length){swiperSlider2x1=new Swiper(swiperSlider2x1,{pagination:'#swiperSlider2x1 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider2x2.length){swiperSlider2x2=new Swiper(swiperSlider2x2,{pagination:'#swiperSlider2x2 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider2x3.length){swiperSlider2x3=new Swiper(swiperSlider2x3,{pagination:'#swiperSlider2x3 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider2x4.length){swiperSlider2x4=new Swiper(swiperSlider2x4,{pagination:'#swiperSlider2x4 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider2x5.length){swiperSlider2x5=new Swiper(swiperSlider2x5,{pagination:'#swiperSlider2x5 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider3x1.length){swiperSlider3x1=new Swiper(swiperSlider3x1,{pagination:'#swiperSlider3x1 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider3x2.length){swiperSlider3x2=new Swiper(swiperSlider3x2,{pagination:'#swiperSlider3x2 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider3x3.length){swiperSlider3x3=new Swiper(swiperSlider3x3,{pagination:'#swiperSlider3x3 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider3x4.length){swiperSlider3x4=new Swiper(swiperSlider3x4,{pagination:'#swiperSlider3x4 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider3x5.length){swiperSlider3x5=new Swiper(swiperSlider3x5,{pagination:'#swiperSlider3x5 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider4x1.length){swiperSlider4x1=new Swiper(swiperSlider4x1,{pagination:'#swiperSlider4x1 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider4x2.length){swiperSlider4x2=new Swiper(swiperSlider4x2,{pagination:'#swiperSlider4x2 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider4x3.length){swiperSlider4x3=new Swiper(swiperSlider4x3,{pagination:'#swiperSlider4x3 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider4x4.length){swiperSlider4x4=new Swiper(swiperSlider4x4,{pagination:'#swiperSlider4x4 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}
if(swiperSlider4x5.length){swiperSlider4x5=new Swiper(swiperSlider4x5,{pagination:'#swiperSlider4x5 .row.car-thumbnails',paginationClickable:true,paginationBulletRender:function(index,className){return'<div class="col-xs-2 col-sm-2 col-md-3 '+ className+'"><a href="#"><img src="'+ rentit_obj.themeurl+'/img/preview/cars/car-70x70x'+(index+ 1)+'.jpg" alt=""/></a></div>';}});}}
if(jQuery.ui){if(jQuery(priceSliderRange).length){var amount=jQuery("#amount");var amount_price=jQuery("#amout_rating");jQuery(priceSliderRange).slider({range:true,min:parseInt(amount.data('min')),max:parseInt(amount.data('max')),values:[amount.data('value_min'),amount.data('value_max')],slide:function(event,ui){amount.val(rentit_obj.currency+ ui.values[0]+" - "+ rentit_obj.currency+ ui.values[1]);amount_price.val(ui.values[0]+','+ ui.values[1]);}});amount.val(rentit_obj.currency+ jQuery("#slider-range").slider("values",0)+" - "+ rentit_obj.currency+ jQuery("#slider-range").slider("values",1));amount_price.val(jQuery("#slider-range").slider("values",0)+","+ jQuery("#slider-range").slider("values",1));}}
jQuery('.car-categories .arrow').on('click',function(event){jQuery(this).parent().parent().find('ul.children').removeClass('active');jQuery(this).parent().parent().find('.fa-angle-up').addClass('fa-angle-down').removeClass('fa-angle-up');if(jQuery(this).parent().find('ul.children').is(":visible")){}
else{jQuery(this).find('.fa-angle-down').addClass('fa-angle-up').removeClass('fa-angle-down');jQuery(this).parent().find('ul.children').addClass('active');}
jQuery(this).parent().parent().find('ul.children').each(function(){if(!jQuery(this).hasClass('active')){jQuery(this).slideFadeOut();}
else{jQuery(this).slideFadeIn();}});});jQuery('.car-categories ul.children').each(function(){if(!jQuery(this).hasClass('active')){jQuery(this).hide();}});jQuery(".ripple-effect").on('click',function(e){var rippler=jQuery(this);if(rippler.find(".ink").length==0){rippler.append("<span class='ink'></span>");}
var ink=rippler.find(".ink");ink.removeClass("animate");if(!ink.height()&&!ink.width()){var d=Math.max(rippler.outerWidth(),rippler.outerHeight());ink.css({height:d,width:d});}
var x=e.pageX- rippler.offset().left- ink.width()/ 2;
var y=e.pageY- rippler.offset().top- ink.height()/ 2;
ink.css({top:y+'px',left:x+'px'}).addClass("animate");})
updater();});jQuery(window).load(function(){jQuery('#status').fadeOut();jQuery('#preloader').delay(200).fadeOut(200);if(jQuery().isotope){isotopeContainer.isotope({itemSelector:'.isotope-item'});isotopeFiltrable.on('click',function(){var selector=jQuery(this).attr('data-filter');isotopeFiltrable.parent().removeClass('current');jQuery(this).parent().addClass('current');isotopeContainer.isotope({filter:selector});return false;});isotopeContainer.isotope('reLayout');}
if(location.hash!=''){var hash='#'+ window.location.hash.substr(1);if(hash.length){body.delay(0).animate({scrollTop:jQuery(hash).offset().top},{duration:1200,easing:"easeInOutExpo"});}}
if(jQuery().owlCarousel){if(hotDealsCarousel.length){hotDealsCarousel.owlCarousel({rtl:rentit_obj.rtl,autoplay:false,loop:true,margin:30,dots:true,nav:false,navText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsive:{0:{items:1},479:{items:1},768:{items:1},991:{items:1},1024:{items:1}}});}}
updater();});function updater(){if(jQuery().sticky){jQuery('.header.fixed').sticky('update');}
if(jQuery().swiper){jQuery('.swiper-container-GREAT-RENTAL').each(function(index,element){jQuery(this).addClass('s'+ index);var slidesPerView=3;if(jQuery(window).width()>991){slidesPerView=3;}
else{if(jQuery(window).width()<768){slidesPerView=1;}
else{slidesPerView=2;}}
var swiper=jQuery('.swiper-container.s'+ index);swiper.swiper({direction:'horizontal',slidesPerView:slidesPerView,spaceBetween:30,loop:true,paginationClickable:true,pagination:'.swiper-pagination',nextButton:'.swiper-button-next',prevButton:'.swiper-button-prev'});if(typeof(swiper.length)=='undefined'){swiper.update();swiper.onResize();}});if(typeof(swiperOffersBest.length)=='undefined'){swiperOffersBest.update();swiperOffersBest.onResize();if(jQuery(window).width()>991){swiperOffersBest.params.slidesPerView=3;}
else{if(jQuery(window).width()<768){swiperOffersBest.params.slidesPerView=1;}
else{swiperOffersBest.params.slidesPerView=2;}}}
if(typeof(swiperOffersPopular.length)=='undefined'){swiperOffersPopular.update();swiperOffersPopular.onResize();if(jQuery(window).width()>991){swiperOffersPopular.params.slidesPerView=3;}
else{if(jQuery(window).width()<768){swiperOffersPopular.params.slidesPerView=1;}
else{swiperOffersPopular.params.slidesPerView=2;}}}
if(typeof(swiperOffersEconomic.length)=='undefined'){swiperOffersEconomic.update();swiperOffersEconomic.onResize();if(jQuery(window).width()>991){swiperOffersEconomic.params.slidesPerView=3;swiperOffersEconomic.stopAutoplay();swiperOffersEconomic.startAutoplay();}
else{if(jQuery(window).width()<768){swiperOffersEconomic.params.slidesPerView=1;swiperOffersEconomic.stopAutoplay();swiperOffersEconomic.startAutoplay();}
else{swiperOffersEconomic.params.slidesPerView=2;swiperOffersEconomic.stopAutoplay();swiperOffersEconomic.startAutoplay();}}}
if(typeof(swiperSlider1x1.length)=='undefined'){swiperSlider1x1.update();swiperSlider1x1.onResize();}
if(typeof(swiperSlider1x2.length)=='undefined'){swiperSlider1x2.update();swiperSlider1x2.onResize();}
if(typeof(swiperSlider1x3.length)=='undefined'){swiperSlider1x3.update();swiperSlider1x3.onResize();}
if(typeof(swiperSlider1x4.length)=='undefined'){swiperSlider1x4.update();swiperSlider1x4.onResize();}
if(typeof(swiperSlider1x5.length)=='undefined'){swiperSlider1x5.update();swiperSlider1x5.onResize();}
if(typeof(swiperSlider2x1.length)=='undefined'){swiperSlider2x1.update();swiperSlider2x1.onResize();}
if(typeof(swiperSlider2x2.length)=='undefined'){swiperSlider2x2.update();swiperSlider2x2.onResize();}
if(typeof(swiperSlider2x3.length)=='undefined'){swiperSlider2x3.update();swiperSlider2x3.onResize();}
if(typeof(swiperSlider2x4.length)=='undefined'){swiperSlider2x4.update();swiperSlider2x4.onResize();}
if(typeof(swiperSlider2x5.length)=='undefined'){swiperSlider2x5.update();swiperSlider2x5.onResize();}
if(typeof(swiperSlider3x1.length)=='undefined'){swiperSlider3x1.update();swiperSlider3x1.onResize();}
if(typeof(swiperSlider3x2.length)=='undefined'){swiperSlider3x2.update();swiperSlider3x2.onResize();}
if(typeof(swiperSlider3x3.length)=='undefined'){swiperSlider3x3.update();swiperSlider3x3.onResize();}
if(typeof(swiperSlider3x4.length)=='undefined'){swiperSlider3x4.update();swiperSlider3x4.onResize();}
if(typeof(swiperSlider3x5.length)=='undefined'){swiperSlider3x5.update();swiperSlider3x5.onResize();}
if(typeof(swiperSlider4x1.length)=='undefined'){swiperSlider4x1.update();swiperSlider4x1.onResize();}
if(typeof(swiperSlider4x2.length)=='undefined'){swiperSlider4x2.update();swiperSlider4x2.onResize();}
if(typeof(swiperSlider4x3.length)=='undefined'){swiperSlider4x3.update();swiperSlider4x3.onResize();}
if(typeof(swiperSlider4x4.length)=='undefined'){swiperSlider4x4.update();swiperSlider4x4.onResize();}
if(typeof(swiperSlider4x5.length)=='undefined'){swiperSlider4x5.update();swiperSlider4x5.onResize();}}
var nowDate=new Date();var today=new Date(nowDate.getFullYear(),nowDate.getMonth(),nowDate.getDate(),0,0,0,0);jQuery('#formSearchUpDate50').datetimepicker();jQuery('#formSearchUpDate60').datetimepicker();jQuery(document).ready(function(){jQuery('#formSearchUpDate').datetimepicker({minDate:today,format:rentit_obj.date_format,locale:rentit_obj.lang});jQuery('#formSearchOffDate').datetimepicker({minDate:today,format:rentit_obj.date_format,locale:rentit_obj.lang});jQuery('#formSearchUpDate2').datetimepicker({minDate:today,format:rentit_obj.date_format,locale:rentit_obj.lang});jQuery('#formSearchOffDate2').datetimepicker({minDate:today,format:rentit_obj.date_format,locale:rentit_obj.lang});jQuery('#formSearchUpDate3').datetimepicker({minDate:today,format:rentit_obj.date_format,disabledDates:rentit_obj.reserved_date,locale:rentit_obj.lang});jQuery('#formSearchOffDate3').datetimepicker({minDate:today,format:rentit_obj.date_format,disabledDates:rentit_obj.reserved_date,locale:rentit_obj.lang});jQuery("#formSearchUpDate2").on("dp.change",function(e){jQuery("#formSearchOffDate2").data("DateTimePicker").minDate(e.date);});jQuery("#formSearchOffDate2").on("dp.change",function(e){jQuery("#formSearchUpDate2").data("DateTimePicker").minDate(e.date);});jQuery("#formSearchUpDate3").on("dp.change",function(e){jQuery("#formSearchOffDate3").data("DateTimePicker").minDate(e.date);});jQuery("#formSearchOffDate3").on("dp.change",function(e){jQuery("#formSearchUpDate3").data("DateTimePicker").minDate(e.date);});jQuery("#formSearchUpDate").on("dp.change",function(e){jQuery("#formSearchOffDate").data("DateTimePicker").minDate(e.date);});jQuery("#formSearchOffDate").on("dp.change",function(e){jQuery("#formSearchUpDate").data("DateTimePicker").minDate(e.date);});jQuery('#formFindCarDate').datetimepicker({format:rentit_obj.date_format,locale:rentit_obj.lang});jQuery('#formSearchOffDate5').datetimepicker({format:rentit_obj.date_format,locale:rentit_obj.lang});jQuery('#formSearchUpDate5').datetimepicker({format:rentit_obj.date_format,locale:rentit_obj.lang});});}
jQuery(window).resize(function(){if(jQuery().isotope){isotopeContainer.isotope('reLayout');}
updater();});jQuery(window).scroll(function(){if(jQuery().sticky){jQuery('.header.fixed').sticky('update');}});jQuery(document).ready(function($){$(document).on("click",'.flag_grey',function(e){if($('div').is('#wpadminbar')){$(this).removeClass('flag_grey');document.cookie="comentid"+ $(this).data('id')+"=1";}});$(document).on("click",'.heart_post_like',function(e){e.preventDefault();var this_a=$(this);var minus=0;if(document.cookie.match(new RegExp("post_like"+ this_a.data('id')))){minus=1;deleteCookie("post_like"+ this_a.data('id'));}else{document.cookie="post_like"+ this_a.data('id')+"=1";}
jQuery.ajax({url:rentit_obj.ajaxurl,type:'POST',data:{action:'rentit_ajax_post_like',id:this_a.data('id'),minus:minus},success:function(html){this_a.html('<i class="fa fa-heart"> </i>'+ html);}});});$('#checkboxa1').click(function(){var $this=$(this);if($this.is(':checked')){$('#reservation_car_btn').prop('disabled',false);}else{$('#reservation_car_btn').prop('disabled',true);}});$('#reservation_car_btn').click(function(){if(rentit_obj.plugin_activate==false){alert(rentit_obj.plugin_error_message);return false;}});$('.rentit_topmenu a[href^="#"]').on('click',function(){var target=$(this.hash);if(target.length){$('html,body').animate({scrollTop:(target.offset().top- navbarAffixHeight+ 1)},1000);return false;}});});function loadajaxonmap(i){jQuery.ajax({url:rentit_obj.ajaxurl,type:'POST',data:{action:'rentit_ajax_get_car_list',GET:rentit_obj.GET,page_no:i,},success:function(html){jQuery(".ajax-car-list").append(html);setTimeout(function(){swiper2.update();},500);}});}
function deleteCookie(name){setCookie(name,"",{expires:-1})}
function setCookie(name,value,options){options=options||{};var expires=options.expires;if(typeof expires=="number"&&expires){var d=new Date();d.setTime(d.getTime()+ expires*1000);expires=options.expires=d;}
if(expires&&expires.toUTCString){options.expires=expires.toUTCString();}
value=encodeURIComponent(value);var updatedCookie=name+"="+ value;for(var propName in options){updatedCookie+="; "+ propName;var propValue=options[propName];if(propValue!==true){updatedCookie+="="+ propValue;}}}